blog/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostsFeed

app_name = "blog"

urlpatterns = [
    path("", views.post_list, name="post_list"),
    # path("", views.PostListView.as_view(), name="post_list"),
    path("<int:year>/<int:month>/<int:day>/<slug:post>/", 
         views.post_detail, name="post_detail"),
    path("<int:id>/", views.post_detail2, name="post_detail2"),
    path('<int:post_id>/share', views.post_share, name="post_share"),
    path('<int:post_id>/commment', views.post_comment, name="post_comment"),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
    path('search/', views.post_search, name='post_search'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSiteMap

sitemaps = {
    'posts': PostSiteMap
}

urlpatterns = [
    path("admin/", admin.site.urls),
    path('__debug__/', include('debug_toolbar.urls')),
    path("blog/", include("blog.urls", namespace="blog")),
    path('', RedirectView.as_view(pattern_name='blog:post_list')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),
]

blog/models.py
from django.db import models as m
from django.db.models.query import QuerySet
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager




# class PublishedManager(m.Manager):
#     def get_queryset(self) -> QuerySet:
#         return super().get_queryset().filter(status=Post.Status.PUBLISHED)


class PublishedManager(m.Manager):
    def get_queryset(self) -> QuerySet:
        return super().get_queryset().filter(status=Post.Status.PUBLISHED)

# Create your models here.
class Post(m.Model):
    class Status(m.TextChoices):
        DRAFT = (
            "DF",
            "Draft",
        )
        PUBLISHED = "PB", "Published"

    title = m.CharField(max_length=200)
    slug = m.SlugField(max_length=200,
                        unique_for_date='publish')
    author = m.ForeignKey(User, on_delete=m.CASCADE, related_name="blog_posts")
    body = m.TextField()
    publish = m.DateTimeField(default=timezone.now)
    created = m.DateTimeField(auto_now_add=True)
    updated = m.DateTimeField(auto_now=True)
    status = m.CharField(max_length=2, choices=Status.choices, default=Status.DRAFT)
    objects = m.Manager()
    published = PublishedManager()
    tags = TaggableManager()

    class Meta:
        ordering = ["-publish"]
        indexes = [m.Index(fields=["-publish"])]

    def __str__(self) -> str:
        return self.title
    
    def get_absolute_url(self):
        return reverse('blog:post_detail', 
                       args=[self.publish.year, 
                             self.publish.month,
                             self.publish.day,
                             self.slug])
        # return reverse('blog:post_detail2',
        #                args=[self.id])


class Comment(m.Model):
    post = m.ForeignKey(Post,
                        on_delete=m.CASCADE,
                        related_name='comments'
    )
    name = m.CharField(max_length=80)
    email = m.EmailField()
    body = m.TextField()
    created = m.DateTimeField(auto_now_add=True)
    updated = m.DateTimeField(auto_now=True)
    active = m.BooleanField(default=True)
    class Meta:
        ordering = ['created']
        indexes = [
            m.Index(fields=['created']),
        ]
        def __str__(self) -> str:
            return f'Comment on {self.name} on {self.post}'

blog/forms.py
from django import forms
from .models import Comment

class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False,
                               widget=forms.Textarea)
    
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'body']

class SearchForm(forms.Form):
    query = forms.CharField()
    fecha = forms.DateField()
    fecha.required = False

    

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank, TrigramSimilarity
from .models import Post, Comment
from django.http import Http404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView
from django.core.mail import send_mail
from .forms import EmailPostForm, CommentForm, SearchForm
from django.views.decorators.http import require_POST
from taggit.models import Tag
from django.db.models import Count
from mysite import env


def post_list(request, tag_slug=None):
    form = SearchForm()
    query = None
    results = []
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            search_vector = SearchVector('title', 'body')
            search_query = SearchQuery(query)
            results = Post.published.annotate(
                search=search_vector,
                rank=SearchRank(search_vector, search_query)
                ).filter(search=search_query).order_by('-rank')
        
    else:
        post_list = Post.published.all()
        paginator = Paginator(post_list, 3)
        page_number = request.GET.get('page', 1)
        tag = None
        if tag_slug:
            tag = get_object_or_404(Tag, slug=tag_slug)
            post_list = post_list.filter(tags__in=[tag])
        # posts = paginator.page(page_number)
        paginator = Paginator(post_list, 3)
        page_number = request.GET.get('page', 1)
        try:
            posts = paginator.page(page_number)
        except PageNotAnInteger:
            posts = paginator.page(1)
        except EmptyPage:
            posts = paginator.page(paginator.num_pages)
        return render(request, "blog/post/list.html", {"posts": posts,
                                                   "tag":tag})
    if form:
        return render(request, 'blog/post/search.html',
                  {'form': form,
                      'query': query,
                      'results': results})


def post_detail(request, year, month, day, post):
    try:
        post = Post.published.get(slug=post,
                                  publish__year=year,
                                  publish__month=month,
                                  publish__day=day)
        comments = post.comments.filter(active=True)
        form = CommentForm()
        post_tags_id = post.tags.values_list('id', flat=True)
        similar_posts = Post.published.filter(tags__in=post_tags_id)\
            .exclude(id=post.id)
        similar_posts = similar_posts.annotate(same_tags=Count('tags'))\
            .order_by('-same_tags', '-publish')[:4]
    
    except Post.DoesNotExist:
        raise Http404("No post found, try harder")
    return render(request, "blog/post/post.html", {"post": post,
                                                   'comments': comments,
                                                   'form': form,
                                                   'similar_posts': similar_posts})


def post_detail2(request, id):
    post = get_object_or_404(Post, id=id, status=Post.Status.PUBLISHED)
    comments = post.comments.filter(active=True)
    form = CommentForm()
    #List of similar posts:
    post_tags_id = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_id).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=
                            Count('tags')).order_by('-same_tags', '-publish')[:4]
    return render(request, "blog/post/post.html", {"post": post,
                                                   'comments': comments,
                                                   'form': form,
                                                   'similar_posts': similar_posts})


class PostListView(ListView):
    """Alternative post list view"""
    queryset = Post.published.all()
    model = Post
    context_object_name = 'posts'
    paginate_by = 3
    template_name = "blog/post/list.html"


def post_share(request, post_id):
    EMAIL_CONF = env.EMAIL_CONF
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)

    sent = False
    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{cd['name']} recommends you read " \
                      f"{post.title}"
            message = f"Read {post.title} at {post_url}\n\n" \
                      f"{cd['name']}\'s comments: {cd['comments']}"
            send_mail(subject, message, EMAIL_CONF["DEFAULT_FROM_EMAIL"],
                      [cd['to']])
            sent = True
    else:
        form = EmailPostForm()

    return render(request, 'blog/post/share.html', {'post': post,
                                                    'form': form,
                                                    'sent': sent})

@require_POST
def post_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    comment = None
    form = CommentForm(data=request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.save()
    return render(request, 'blog/post/comment.html',
                  {'post':post,
                   'form':form,
                   'comment':comment})

def post_search(request):
    form = SearchForm()
    query = None
    results = []
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            # search_vector = SearchVector('title', 'body')
            search_vector = SearchVector('title', weight='A') +\
                SearchVector('body', weight='A')
                #SearchVector('body', weight='B') #when weight='B", not working
            search_query = SearchQuery(query)
            results = Post.published.annotate(
                search=search_vector,
                rank=SearchRank(search_vector, search_query)
                # ).filter(search=search_query).order_by('-rank')
                ).filter(rank__gte=0.3).order_by('-rank')
    return render(request, 'blog/post/search.html',
                  {'form': form,
                      'query': query,
                      'results': results})

def post_search(request):
    form = SearchForm()
    query = None
    results = []
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            results = Post.published.annotate(
                similarity=TrigramSimilarity('title', query)
                ).filter(similarity__gte=0.1).order_by('-similarity')
    return render(request, 'blog/post/search.html',
                  {'form': form,
                      'query': query,
                      'results': results})

blog/templates/blog/post/comment.html
{% extends 'blog/base.html' %}
{% block title %}Add comment{% endblock %}
{% block content %}
    {% if comment %}
        <h2>Your comment has been added</h2>
        <p><a href="{{ post.get_absolute_url }}"><Back to the post/a></p>
    {% else %}
        {% include "blog/post/includes/comment_form.html" %}
    {% endif %}
{% endblock %}

blog/templates/blog/post/hello.html
<h1>Hello</h1>

blog/templates/blog/post/latest_posts.html
<ul>
    {% for post in latest_posts%}
    <li>
        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    </li>    
    {% endfor %}       
</ul>

blog/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{% block title %}My Blog{% endblock %}
{% block content %}
<h1>My Blog</h1>
    {% if tag %}
    <h2>Posts tagged with "{{ tag.name }}"</h2>
    {% endif %}
    {% for post in posts %}
        <h2>
            <a href="{{ post.get_absolute_url }}">
                {{ post.title }}
            </a>
        </h2>
        <h3>
            <a href="{% url 'blog:post_detail2' post.id %}">
                        {{ post.title }}
            </a> 
        </h3>
        {% include "blog/post/includes/tags.html" %}
        <p class="date">
            Published {{ post.publish }} by {{ post.author }}
        </p>
        {{ post.body|markdown|truncatewords_html:30|linebreaks }}
    {% endfor %}
    {% include "pagination.html" with page=posts %}
{% endblock %}

blog/templates/blog/post/post.html
{% extends 'blog/base.html' %}
{% load blog_tags %}
{% block title %}{{ post.title }}{% endblock %}
{% block content %}
    <h1>{{ post.title }}</h1>
    <p class="date">
        Published {{ post.publish }} by {{ post.author }}
    </p>
    {{ post.body|markdown }}
    <p>
        <a href="{% url "blog:post_share" post.id %}">
        Share this post
        </a>
    </p>
    <h2>Similar posts</h2>
    {% for post in similar_posts %}
        <p>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </p>
    {% empty %}
        There are no similar posts yet.
    {% endfor %}

    {% with comments.count as total_comments %}
        <h2>
            {{ total_comments }} comment{{ total_comments|pluralize }}
        </h2>
    {% endwith %}
    {% for comment in comments %}
        <div class="commment">
            <p class="info">
                comment {{ forloop.counter }} by {{ comment.name }}
                {{ comment.created }}
            </p>
            {{ comment.body|linebreaks}}
        </div>
    {% empty %}
        <p>There are no comments</p>
    {% endfor %}
    {% include "blog/post/includes/tags.html" %}
    {% include "blog/post/includes/comment_form.html" %}
{% endblock %}

blog/templates/blog/post/search.html
{%  extends 'blog/base.html' %}
{% load blog_tags %}
{% block title %}Search{% endblock %}
{% block content %}
    {% if query %}
        <h1>Posts containing "{{ query }}"</h1>
        <h3>
            {% with results.count as total_results %}
            Found {{ total_results }} result{{ total_results|pluralize }}
            {% endwith %}
        </h3>
        {% for post in results %}
            <h4>
                <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
            </h4>
            {{ post.body|markdown|truncatewords_html:12 }}
        {% empty %}
            <p>There are no results for your query.</p>
        {% endfor %}
        <p><a href="{% url "blog:post_search" %}">Search</a></p>
    {% else %}
        <h1>Search for posts</h1>
        <form method="get">
            {{ form.as_p }}
            <input type="submit" value="Search">
        </form>
    {% endif %}
{% endblock %}

blog/templates/blog/post/share.html
{% extends "blog/base.html" %}

{% block title %}Share a post{% endblock %}

{% block content %}
  {% if sent %}
    <h1>E-mail successfully sent</h1>
    <p>
      "{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}.
    </p>
  {% else %}
    <h1>Share "{{ post.title }}" by e-mail</h1>
    <form method="post" novalidate>
      {{ form.as_p }}
      {% csrf_token %}
      <input type="submit" value="Send e-mail">
      <!-- <button type="submit">Send e-mail</button> -->
    </form>
  {% endif %}
{% endblock %}